#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE "$CKAN_DB_USER" NOSUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '$CKAN_DB_PASSWORD';
    CREATE DATABASE "$CKAN_DB" OWNER "$CKAN_DB_USER" ENCODING 'utf-8';
    CREATE EXTENSION POSTGIS;
    ALTER VIEW geometry_columns OWNER TO "$CKAN_DB_USER";
    GRANT ALL PRIVILEGES ON geometry_columns TO "$POSTGRES_USER";
    ALTER TABLE spatial_ref_sys OWNER TO "$CKAN_DB_USER";
    GRANT ALL PRIVILEGES ON spatial_ref_sys TO "$POSTGRES_USER";
EOSQL
